service: sls-template

custom:
  # Initial setting value.
  const:
    DYNAMO_DB_TABLE_NAME: account_list
    FUNCTION_EVENTS_S3_BUCKET: hoge-bucket-foo-bar
  # AWS Local
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-1
  stage: dev
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:Scan'
        - 'dynamodb:Query'
        - 's3:*'
      Resource: '*'

package:
  exclude:
    - testdata/**
    - node_modules/**
    - migrations/**
    - s3tmp/**
    - .dynamodb/**
    - .eslintrc.js

functions:
  hello:
    handler: handler.hello
    events:
      - s3:
          bucket: ${self:custom.const.FUNCTION_EVENTS_S3_BUCKET}
          event: s3:ObjectCreated:*
      - s3:
          bucket: ${self:custom.const.FUNCTION_EVENTS_S3_BUCKET}
          event: s3:ObjectRemoved:*
    environment:
      TZ: Asia/Tokyo

plugins:
  - serverless-dynamodb-local

resources:
  Resources:
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.const.DYNAMO_DB_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: "S"
        KeySchema:
          - AttributeName: key
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
